# Form implementation generated from reading ui file 'C:\Users\tapia\Desktop\IndustrialEngeenering\Second_2023-1\Programacion Avanzada\Clase 05_05_2013\2 AdmonFacultad\2 AdmonFacultad\Diseno\DPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 420)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BTerminar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BTerminar.setGeometry(QtCore.QRect(370, 350, 619, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BTerminar.setFont(font)
        self.BTerminar.setObjectName("BTerminar")
        self.LTitulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.LTitulo.setGeometry(QtCore.QRect(110, 30, 617, 33))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(18)
        self.LTitulo.setFont(font)
        self.LTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LTitulo.setObjectName("LTitulo")
        self.BFuente = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BFuente.setGeometry(QtCore.QRect(10, 90, 341, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BFuente.setFont(font)
        self.BFuente.setObjectName("BFuente")
        self.BFuente_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BFuente_2.setGeometry(QtCore.QRect(380, 90, 341, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BFuente_2.setFont(font)
        self.BFuente_2.setObjectName("BFuente_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Proyectos de Facultad"))
        self.BTerminar.setText(_translate("MainWindow", "Terminar"))
        self.LTitulo.setText(_translate("MainWindow", "ADMINISTRACIÓN PROYECTOS FACULTAD"))
        self.BFuente.setText(_translate("MainWindow", "Fuente"))
        self.BFuente_2.setText(_translate("MainWindow", "Profesores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
